### ISSUE TITLE
Can I get the ocotvox skill also for the amazon.de skill store

### ISSUE THREAD

**Issue by juergenschubert** [johnnyruz/OctoPrint-OctoVox#10]
Not available in Germany

**Comment by johnnyruz** [comment]
Issue #5 was created to address this since I need to create a specific deployment for each region. 

A question for anyone, do you care if the responses are in English for the German version of the skill (yet to be determined if Amazon will approve it)? 

Otherwise I'm working on centralizing all of the strings for the skill in a configuration store that I can then leverage the community to translate. The Skill will then be able to dynamically use the appropriate phrases for the configured Alexa language.

**Comment by terrorhai** [comment]
Thats no problem, the community will translate it :)

**Comment by juergenschubert** [comment]
English is fine for the .de store

**Comment by johnnyruz** [comment]
Should now be live in the DE store. Let me know if you hear any issues!
